version: 1
disable_existing_loggers: False
formatters:
  colored:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s%(asctime)s %(name)s %(message)s%(reset)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    log_colors:
      DEBUG: blue
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red,bg_white
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stderr
loggers:
  httpcore: {level: WARN}
  httpx: {level: WARN}
  urllib3.connectionpool: {level: WARN}
root:
  level: DEBUG
  handlers: [console]
