#!/bin/bash
set -eu

uvx pyclean --debris all --folders .

poetry install
./update-translations
.venv/bin/python3 -m build
(cd services/open-webui; .venv/bin/python3 -m build)
(cd services/open-webui-pipelines; poetry build)
