#!/bin/sh
set -eu

BUNDLE=dist/linux

mkdir -p $BUNDLE
mkdir -p $BUNDLE/services/ollama/dist
mkdir -p $BUNDLE/services/qdrant/target/release

cp services/ollama/dist/ollama $BUNDLE/services/ollama/dist/

cp services/qdrant/target/release/qdrant $BUNDLE/services/qdrant/target/release/

export PYAPP_DISTRIBUTION_EMBED=true
#export PYAPP_FULL_ISOLATION=true

.venv/bin/python3 -m build
(cd pyapp; PYAPP_PYTHON_VERSION=3.13 PYAPP_PROJECT_NAME=learn2rag PYAPP_PROJECT_PATH=../dist/learn2rag-0.1.0.tar.gz cargo build --release)
cp pyapp/target/release/pyapp $BUNDLE/configurator

(cd services/basic-pipeline; poetry build)
(cd pyapp; PYAPP_PYTHON_VERSION=3.13 PYAPP_PROJECT_NAME=basic-pipeline PYAPP_PROJECT_PATH=../services/basic-pipeline/dist/basic_pipeline-0.1.0.tar.gz PYAPP_EXEC_MODULE=app cargo build --release)
cp pyapp/target/release/pyapp $BUNDLE/services/start-basic-pipeline

(cd services/open-webui; .venv/bin/python3 -m build)
(cd pyapp; PYAPP_PYTHON_VERSION=3.11 PYAPP_PROJECT_NAME=open-webui PYAPP_PROJECT_PATH=../services/open-webui/dist/open_webui-0.6.15.tar.gz PYAPP_EXEC_SPEC=open_webui:app cargo build --release)
cp pyapp/target/release/pyapp $BUNDLE/services/start-open-webui

(cd services/open-webui-pipelines; poetry build)
(cd pyapp; PYAPP_PYTHON_VERSION=3.11 PYAPP_PROJECT_NAME=open-webui-pipelines PYAPP_PROJECT_PATH=../services/open-webui-pipelines/dist/open_webui_pipelines-0.1.0.tar.gz PYAPP_EXEC_MODULE=start cargo build --release)
cp pyapp/target/release/pyapp $BUNDLE/services/start-open-webui-pipelines
