version: '3.3'
services:
  open-webui:
    # ghcr.io/open-webui/open-webui:main
    image: hub.cs.upb.de/dice-research/images/open-webui@sha256:a7368a98dcc4e439575d991b25770bfc73188da6e50020dad3911caffa8c48c7
    environment:
      ENABLE_PERSISTENT_CONFIG: "False"
      DEFAULT_PROMPT_SUGGESTIONS: '[{"title": ["KI-Gesetz", "Warum reguliert"], "content": "Warum muss die Verwendung künstlicher Intelligenz reguliert werden?"}]'
      ENABLE_TITLE_GENERATION: "False"
      OFFLINE_MODE: "True"
      USER_PERMISSIONS_CHAT_FILE_UPLOAD: "False"
      USER_PERMISSIONS_CHAT_TEMPORARY_ENFORCED: "True"
      USER_PERMISSIONS_FEATURES_CODE_INTERPRETER: "False"
      USER_PERMISSIONS_FEATURES_IMAGE_GENERATION: "False"
      USER_PERMISSIONS_FEATURES_WEB_SEARCH: "False"
      WEBUI_NAME: "Learn2RAG"
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
  open-webui-pipelines:
    # ghcr.io/open-webui/pipelines:main
    image: hub.cs.upb.de/dice-research/images/open-webui-pipelines@sha256:53858fbba70f55171d21eff5820f202cac43babf4e627f01472105407982d49a
    environment:
      PIPELINES_URLS: "https://github.com/open-webui/pipelines/blob/48ddbec455de76fc43224daf3438537cd8fcde87/examples/pipelines/integrations/langgraph_pipeline/langgraph_stream_pipeline.py"
    ports:
      - "9098:9098"
    volumes:
      - open-webui-pipelines:/app/pipelines
  qdrant:
    image: qdrant/qdrant:v1.14.1
    restart: always
    container_name: qdrant
    ports:
      - 6336:6333
      - 6334:6334
    expose:
      - 6336
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
volumes:
  open-webui-data:
  open-webui-pipelines:
configs:
  qdrant_config:
    content: |
      log_level: INFO
