version: '3.3'
services:
  open-webui:
    # ghcr.io/open-webui/open-webui:main
    image: hub.cs.upb.de/dice-research/images/open-webui@sha256:a7368a98dcc4e439575d991b25770bfc73188da6e50020dad3911caffa8c48c7
    environment:
      ENABLE_PERSISTENT_CONFIG: "False"
      DEFAULT_PROMPT_SUGGESTIONS: '[{"title": ["KI-Gesetz", "Warum reguliert"], "content": "Warum muss die Verwendung künstlicher Intelligenz reguliert werden?"}]'
      ENABLE_TITLE_GENERATION: "False"
      OFFLINE_MODE: "True"
      USER_PERMISSIONS_CHAT_FILE_UPLOAD: "False"
      USER_PERMISSIONS_CHAT_TEMPORARY_ENFORCED: "True"
      USER_PERMISSIONS_FEATURES_CODE_INTERPRETER: "False"
      USER_PERMISSIONS_FEATURES_IMAGE_GENERATION: "False"
      USER_PERMISSIONS_FEATURES_WEB_SEARCH: "False"
      WEBUI_NAME: "Learn2RAG"
    ports:
      - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
  open-webui-pipelines:
    # ghcr.io/open-webui/pipelines:main
    image: hub.cs.upb.de/dice-research/images/open-webui-pipelines@sha256:53858fbba70f55171d21eff5820f202cac43babf4e627f01472105407982d49a
    environment:
      PIPELINES_URLS: "https://github.com/open-webui/pipelines/blob/48ddbec455de76fc43224daf3438537cd8fcde87/examples/pipelines/integrations/langgraph_pipeline/langgraph_stream_pipeline.py"
    ports:
      - "9099:9099"
    volumes:
      - open-webui-pipelines:/app/pipelines
  redis:
    # redis/redis-stack:7.4.0-v5
    image: hub.cs.upb.de/dice-research/images/redis-stack:7.4.0-v5
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  langgraph:
    build: .
    environment:
      LANGCHAIN_API_KEY: 1
      LANGCHAIN_TRACING_V2: "false"
      LLM_API_PROXY: ${LLM_API_PROXY}
      LLM_API_URL: ${LLM_API_URL}
      LLM_API_TOKEN: ${LLM_API_TOKEN}
      LLM_API_MODEL: ${LLM_API_MODEL}
      REDIS_URL: redis://redis:6379
      REDIS_INDEX_NAME: ${REDIS_INDEX_NAME}
      PROMPT_FILE: ./prompts/langsmithhub/rlm/rag-prompt.json
volumes:
  open-webui-data:
  open-webui-pipelines:
  redis-data:
