#!/bin/bash
set -eu
python3 -m venv .venv
.venv/bin/pip install -e .
(cd services/open-webui && bash -eu ../install-open-webui)
(cd services/open-webui-pipelines && bash -eu ../install-open-webui-pipelines)
(cd services/importer && bash -eu ../install-importer)
(cd services/basic-pipeline && bash -eu ../install-basic-pipeline)
(cd services/redis && BUILD_TLS=yes BUILD_WITH_MODULES=yes INSTALL_RUST_TOOLCHAIN=yes DISABLE_WERRORS=yes make -j "$(nproc)" all)
(cd services/ollama && bash -eu ../install-ollama)
