#!/bin/bash
set -eu

./build-python
VERSION=$(uv version --short)
# 64-bit Linux (kernel 3.2+, glibc 2.17+)
# https://doc.rust-lang.org/rustc/platform-support.html#tier-1-with-host-tools
# https://github.com/cross-rs/cross#supported-targets
# See also: pyapp/Cross.toml
CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu
# https://github.com/cross-rs/cross/wiki/FAQ#glibc-version-error
CARGO_TARGET_DIR=target/build/"${CARGO_BUILD_TARGET}"

BUNDLE_DIR=~/.cache/learn2rag-dist
BUNDLE_NAME=learn2rag-linux
BUNDLE=$BUNDLE_DIR/$BUNDLE_NAME

rm -rf $BUNDLE
mkdir -p $BUNDLE
mkdir -p $BUNDLE/services

export PYAPP_DISTRIBUTION_EMBED=true
export PYAPP_FULL_ISOLATION=false
export PYAPP_EXPOSE_ALL_COMMANDS=true

echo "Clearing Cargo cache..."
(cd pyapp && cross clean)

# Bake the relative offline path directly into the binaries
OFFLINE_ARGS="--no-index --find-links=./services/wheels"

# Build Learn2RAG
cp dist/learn2rag-$VERSION-py3-none-any.whl pyapp
(cd pyapp; \
    PYAPP_PYTHON_VERSION=3.13 \
    PYAPP_PROJECT_NAME=learn2rag \
    PYAPP_PROJECT_PATH=learn2rag-$VERSION-py3-none-any.whl \
    PYAPP_PIP_EXTRA_ARGS="$OFFLINE_ARGS" \
    cross build --release --target $CARGO_BUILD_TARGET)
cp pyapp/target/$CARGO_BUILD_TARGET/release/pyapp $BUNDLE/configurator

cp services/start-import.linux $BUNDLE/services/start-import

# Build Open WebUI
cp services/open-webui/dist/open_webui-0.6.15-py3-none-any.whl pyapp
(cd pyapp; \
    PYAPP_PYTHON_VERSION=3.11 \
    PYAPP_PROJECT_NAME=open-webui \
    PYAPP_PROJECT_PATH=open_webui-0.6.15-py3-none-any.whl \
    PYAPP_EXEC_SPEC=open_webui:app \
    PYAPP_PIP_EXTRA_ARGS="$OFFLINE_ARGS" \
    cross build --release --target $CARGO_BUILD_TARGET)
cp pyapp/target/$CARGO_BUILD_TARGET/release/pyapp $BUNDLE/services/start-open-webui

# Build Open WebUI Pipelines
cp services/open-webui-pipelines/dist/open_webui_pipelines-0.1.0-py3-none-any.whl pyapp
(cd pyapp; \
    PYAPP_PYTHON_VERSION=3.11 \
    PYAPP_PROJECT_NAME=open-webui-pipelines \
    PYAPP_PROJECT_PATH=open_webui_pipelines-0.1.0-py3-none-any.whl \
    PYAPP_EXEC_MODULE=start \
    PYAPP_PIP_EXTRA_ARGS="$OFFLINE_ARGS" \
    cross build --release --target $CARGO_BUILD_TARGET)
cp pyapp/target/$CARGO_BUILD_TARGET/release/pyapp $BUNDLE/services/start-open-webui-pipelines

while read -u 100 file; do
    mkdir -p $BUNDLE/$(dirname $file)
    cp -r $file $BUNDLE/$file
done 100<Distfiles

wget --continue -O $BUNDLE_DIR/ollama-linux.tgz https://github.com/ollama/ollama/releases/download/v0.12.1/ollama-linux-amd64.tgz
mkdir -p $BUNDLE/services/ollama
tar -C $BUNDLE/services/ollama -xzvf $BUNDLE_DIR/ollama-linux.tgz

wget --continue -O $BUNDLE_DIR/qdrant-linux.tar.gz https://github.com/qdrant/qdrant/releases/download/v1.15.4/qdrant-x86_64-unknown-linux-musl.tar.gz
mkdir -p $BUNDLE/services/qdrant
tar -C $BUNDLE/services/qdrant -xzvf $BUNDLE_DIR/qdrant-linux.tar.gz

WHEELS_DIR=$BUNDLE/services/wheels
mkdir -p $WHEELS_DIR

echo "Downloading offline dependencies..."
rm -rf $BUNDLE_DIR/venv313 $BUNDLE_DIR/venv311
uv venv --seed --python 3.13 $BUNDLE_DIR/venv313
uv venv --seed --python 3.11 $BUNDLE_DIR/venv311
$BUNDLE_DIR/venv311/bin/python -m pip download wheel setuptools -d $WHEELS_DIR
$BUNDLE_DIR/venv313/bin/python -m pip download dist/learn2rag-$VERSION-py3-none-any.whl -d $WHEELS_DIR
$BUNDLE_DIR/venv311/bin/python -m pip download services/open-webui/dist/open_webui-0.6.15-py3-none-any.whl -d $WHEELS_DIR
$BUNDLE_DIR/venv311/bin/python -m pip download services/open-webui-pipelines/dist/open_webui_pipelines-0.1.0-py3-none-any.whl -d $WHEELS_DIR

rm -rf $BUNDLE_DIR/venv313 $BUNDLE_DIR/venv311

cp start.linux $BUNDLE/start
cp uninstall.linux $BUNDLE/uninstall

# https://docs.github.com/en/actions/reference/workflows-and-actions/variables#default-environment-variables
[ -z "${GITHUB_ACTIONS-}" ] && (cd $BUNDLE_DIR; zip -r $BUNDLE_NAME $BUNDLE_NAME)
