#!/bin/bash
set -eu

# 64-bit MinGW (Windows 10+, Windows Server 2016+)
# https://doc.rust-lang.org/rustc/platform-support.html#tier-1-with-host-tools
CARGO_BUILD_TARGET=x86_64-pc-windows-gnu
BIN_SUFFIX=.exe

. ./package-common

#cp services/start-import.windows.bat $BUNDLE/services/start-import.bat

wget --continue -O $BUNDLE_DIR/ollama-windows.zip https://github.com/ollama/ollama/releases/download/v0.12.1/ollama-windows-amd64.zip
mkdir -p $BUNDLE/services/ollama
unzip -o $BUNDLE_DIR/ollama-windows.zip -d $BUNDLE/services/ollama

wget --continue -O $BUNDLE_DIR/qdrant-windows-v1.17.1.zip https://github.com/qdrant/qdrant/releases/download/v1.17.1/qdrant-x86_64-pc-windows-msvc.zip
mkdir -p $BUNDLE/services/qdrant
unzip -o $BUNDLE_DIR/qdrant-windows-v1.17.1.zip -d $BUNDLE/services/qdrant

cp start.windows.bat $BUNDLE/start.bat
cp uninstall.windows.bat $BUNDLE/uninstall.bat

# https://docs.github.com/en/actions/reference/workflows-and-actions/variables#default-environment-variables
[ -z "${GITHUB_ACTIONS-}" ] && (cd $BUNDLE_DIR; zip -r $BUNDLE_NAME $BUNDLE_NAME)
