#!/bin/bash
set -eu

BUNDLE_NAME=learn2rag-$(echo $CARGO_BUILD_TARGET |cut -d '-' -f 3)

./build-python
VERSION=$(uv version --short)

# https://github.com/cross-rs/cross/wiki/FAQ#glibc-version-error
CARGO_TARGET_DIR=target/build/"${CARGO_BUILD_TARGET}"

BUNDLE_DIR=~/.cache/learn2rag-dist
BUNDLE=$BUNDLE_DIR/$BUNDLE_NAME
rm -rf $BUNDLE

mkdir -p $BUNDLE
mkdir -p $BUNDLE/services

export PYAPP_DISTRIBUTION_EMBED=true
export PYAPP_FULL_ISOLATION=false
export PYAPP_EXPOSE_ALL_COMMANDS=true

echo "Clearing Cargo cache..."
(cd pyapp && cross clean)

# Bake the relative offline path directly into the binaries
OFFLINE_ARGS="--no-index --find-links=./services/wheels"

cp dist/learn2rag-$VERSION-py3-none-any.whl pyapp
(cd pyapp; \
    PYAPP_PYTHON_VERSION=3.13 \
    PYAPP_PROJECT_NAME=learn2rag \
    PYAPP_PROJECT_PATH=learn2rag-$VERSION-py3-none-any.whl \
    PYAPP_PIP_EXTRA_ARGS="$OFFLINE_ARGS" \
    cross build --release --target $CARGO_BUILD_TARGET)
cp pyapp/target/$CARGO_BUILD_TARGET/release/pyapp$BIN_SUFFIX $BUNDLE/configurator$BIN_SUFFIX

cp services/open-webui/dist/open_webui-0.6.15-py3-none-any.whl pyapp
(cd pyapp; \
    PYAPP_PYTHON_VERSION=3.11 \
    PYAPP_PROJECT_NAME=open-webui \
    PYAPP_PROJECT_PATH=open_webui-0.6.15-py3-none-any.whl \
    PYAPP_EXEC_SPEC=open_webui:app \
    PYAPP_PIP_EXTRA_ARGS="$OFFLINE_ARGS" \
    cross build --release --target $CARGO_BUILD_TARGET)
cp pyapp/target/$CARGO_BUILD_TARGET/release/pyapp$BIN_SUFFIX $BUNDLE/services/start-open-webui$BIN_SUFFIX

while read -u 100 file; do
    mkdir -p $BUNDLE/$(dirname $file)
    cp -r $file $BUNDLE/$file
done 100<Distfiles

WHEELS_DIR=$BUNDLE/services/wheels
mkdir -p $WHEELS_DIR

rm -rf $BUNDLE_DIR/venv313 $BUNDLE_DIR/venv311
uv venv --seed --python 3.13 $BUNDLE_DIR/venv313
uv venv --seed --python 3.11 $BUNDLE_DIR/venv311
$BUNDLE_DIR/venv311/bin/python -m pip download wheel setuptools -d $WHEELS_DIR
$BUNDLE_DIR/venv313/bin/python -m pip download dist/learn2rag-$VERSION-py3-none-any.whl -d $WHEELS_DIR
$BUNDLE_DIR/venv311/bin/python -m pip download services/open-webui/dist/open_webui-0.6.15-py3-none-any.whl -d $WHEELS_DIR
rm -rf $BUNDLE_DIR/venv313 $BUNDLE_DIR/venv311
