@echo off
rem
echo Starting Learn2RAG...
echo Initializing, please wait...
echo ========================================
echo 1/3 Initializing open-webui...
services\start-open-webui main --version
echo ========================================
echo 2/3 Initializing open-webui-pipelines...
services\start-open-webui-pipelines init
echo ========================================
echo 3/3 Initializing and starting Learn2RAG...
set FLASK_DEBUG=1
.\configurator
