#!/bin/sh
set -eu
PYBABEL="uv run pybabel"
$PYBABEL extract --mapping-file=learn2rag/ui/babel.cfg \
         --no-location --omit-header --sort-output \
         --output-file=learn2rag/ui/messages.pot learn2rag/ui
$PYBABEL update --input-file=learn2rag/ui/messages.pot \
         --no-fuzzy-matching --omit-header \
         --output-dir=learn2rag/ui/translations
$PYBABEL compile --directory=learn2rag/ui/translations
