name: pipeline
label: RAG
ports:
  # TODO: labels in the interface currently assume a specific port order
  - ui
  - qdrant_http
  - pipeline
  - open_webui_pipelines
ui_url: 'http://{{learn2rag_hostname}}:{{ports.ui}}/'
files:
  - path: '{{storage_path}}/basic_user_config.json'
    content: |
      {
          "collection_name": "learn2rag",
          "llm": "{{language_model.model}}"
      }

services:
  open-webui:
    working_dir: '{{storage_path}}'
    command:
      - '{{learn2rag_path}}/services/start-open-webui{% if is_windows %}.exe{% endif %}'
      - 'serve'
      - '--host'
      - '0.0.0.0'
      - '--port'
      - '{{ports.ui}}'
    environment:
      LEARN2RAG_PATH: '{{learn2rag_path}}'
      DATA_DIR: '{{storage_path}}/open-webui-data'
      DEFAULT_LOCALE: 'de'
      ENABLE_OPENAI_API: 'True'
      OPENAI_API_BASE_URL: 'http://localhost:{{ports.open_webui_pipelines}}'
      OPENAI_API_KEY: '0p3n-w3bu!'
      ENABLE_OLLAMA_API: 'False'
      ENABLE_PERSISTENT_CONFIG: 'False'
      ENABLE_SIGNUP: 'True'
      ENABLE_TITLE_GENERATION: 'False'
      OFFLINE_MODE: 'True'
      USER_PERMISSIONS_CHAT_FILE_UPLOAD: 'False'
      USER_PERMISSIONS_CHAT_TEMPORARY_ENFORCED: 'True'
      USER_PERMISSIONS_FEATURES_CODE_INTERPRETER: 'False'
      USER_PERMISSIONS_FEATURES_IMAGE_GENERATION: 'False'
      USER_PERMISSIONS_FEATURES_WEB_SEARCH: 'False'
      # https://docs.openwebui.com/getting-started/env-configuration/#webui_auth
      # "turning off authentication is only possible for fresh installations without any existing users"
      WEBUI_AUTH: 'False'
      WEBUI_NAME: 'Learn2RAG'
    healthcheck:
      # TODO: We only support ['CMD', 'curl', '-f', ...]
      test: ['CMD', 'curl', '-f', 'http://localhost:{{ports.ui}}/health']
  # # Only needed if WEBUI_AUTH is True for open-webui
  # open-webui-setup:
  #   working_dir: '{{storage_path}}'
  #   command: ['bash', '-eu', '{{learn2rag_path}}/services/setup-open-webui']
  #   environment:
  #     WEBUI_URL: 'http://localhost:{{ports.ui}}/'
  #     ADMIN_USER_EMAIL: 'user@learn2rag.de'
  #     ADMIN_USER_PASSWORD: 'learn2rag'
  openwebui-pipelines:
    working_dir: 'services/open-webui-pipelines'
    command: ['{{learn2rag_path}}/services/start-open-webui-pipelines{% if is_windows %}.exe{% endif %}']
    environment:
      LEARN2RAG_PATH: '{{learn2rag_path}}'
      PIPELINE_STREAM_URL: 'http://127.0.0.1:{{ports.pipeline}}/stream'
      PIPELINES_DIR: '{{learn2rag_path}}/open-webui-pipelines'
      HOST: '127.0.0.1'
      PORT: '{{ports.open_webui_pipelines}}'
  qdrant:
    working_dir: '{{storage_path}}'
    command:
      - '{{learn2rag_path}}/services/qdrant/qdrant{% if is_windows %}.exe{% endif %}'
      - '--config-path'
      - '{{learn2rag_path}}/qdrant/config.yml'
    environment:
      # https://qdrant.tech/documentation/guides/configuration/
      QDRANT__LOG_LEVEL: 'INFO'
      QDRANT__SERVICE__HOST: '127.0.0.1'
      QDRANT__SERVICE__HTTP_PORT: '{{ports.qdrant_http}}'
      QDRANT__TELEMETRY_DISABLED: 'true'
  main:
    working_dir: '{{storage_path}}'
    command: '{{learn2rag_path}}/services/start-basic-pipeline{% if is_windows %}.exe{% endif %}'
    environment:
      LEARN2RAG_PATH: '{{learn2rag_path}}'
      LEARN2RAG_PIPELINE_PORT: '{{ports.pipeline}}'
      QDRANT__SERVICE__HTTP_PORT: '{{ports.qdrant_http}}'
      PIPELINE_USER_CONFIG: '{{storage_path}}/basic_user_config.json'
      PIPELINE_OPT_CONFIG: '{{learn2rag_path}}/services/basic-pipeline/opt_config.json'
      LANGCHAIN_API_KEY: '1'
      LANGCHAIN_TRACING_V2: 'false'
      LLM_API_TYPE: '{{language_model.api}}'
      LLM_API_URL: '{{language_model.url}}'
      LLM_API_TOKEN: '{{language_model.token}}'
      LLM_API_MODEL: '{{language_model.model}}'
