name: pipeline
label: RAG
ports:
  # TODO: labels in the interface currently assume a specific port order
  - ui
  - qdrant_http
  - pipeline
  - open_webui_pipelines
ui_url: '{{learn2rag_scheme}}://{{learn2rag_hostname}}:{{ports.ui}}/'
files:
  - path: '{{storage_path}}/qdrant_config.yml'
    content: |
      log_level: INFO
      service:
        api_key: '{{qdrant_api_key}}'
        grpc_port: null
        http_port: '{{ports.qdrant_http}}'
        host: '127.0.0.1'
      telemetry_disabled: true
  - path: '{{storage_path}}/basic_user_config.json'
    content: |
      {
          "collection_name": "learn2rag",
          "imported_documents_file_path": "loaded_documents.json",
          "llm": "{{language_model.model}}",
          "qdrant": {
              "api_key": "{{qdrant_api_key}}"
          }
      }

  - path: '{{storage_path}}/logging_config.yml'
    content: |
      version: 1
      formatters:
        simple:
          format: "%(asctime)s %(levelname)-8s %(name)s %(message)s"
        colored:
          class: colorlog.ColoredFormatter
          format: "%(log_color)s%(asctime)s %(levelname)-8s %(name)s %(message)s"
        profiling:
          format: "%(created)f %(request_id)s %(activity)s %(message)s"
      handlers:
        display:
          class: logging.StreamHandler
          level: INFO
          formatter: colored
          stream: ext://sys.stderr
        profiling_display:
          class: logging.StreamHandler
          formatter: profiling
          stream: ext://sys.stderr
        profiling_file:
          class: logging.FileHandler
          formatter: profiling
          filename: '{{storage_path}}/logs/profiling.log'
          encoding: utf-8
        errors_file:
          class: logging.FileHandler
          level: ERROR
          formatter: simple
          filename: '{{storage_path}}/logs/error.log'
          encoding: utf-8
        {% if debug_logging %}
        debug_file:
          class: logging.FileHandler
          level: DEBUG
          formatter: simple
          filename: '{{storage_path}}/logs/debug.log'
          encoding: utf-8
        {% endif %}
      loggers:
        profiling:
          handlers:
            - profiling_display
            - profiling_file
          propagate: no
      root:
        level: DEBUG
        handlers:
          - display
          - errors_file
          {% if debug_logging %}
          - debug_file
          {% endif %}

  - path: '{{storage_path}}/logs/.keep'
    content: ''

#      - '{{learn2rag_path}}/services/start-open-webui{% if is_windows %}.exe{% endif %}'
#Bypass the bash wrapper and run Uvicorn natively ( TODO: remove if not work)
services:
  open-webui:
    working_dir: '{{storage_path}}'
    command:
      - 'sh'
      - '-c'
      - >
        mkdir -p '{{storage_path}}/open-webui-data' &&
        {% if use_ssl %}
        exec {{learn2rag_path}}/services/open-webui/.venv/bin/uvicorn open_webui.main:app --host 0.0.0.0 --port {{ports.ui}} --forwarded-allow-ips '*' --ssl-certfile '{{ssl_cert}}' --ssl-keyfile '{{ssl_key}}'
        {% else %}
        exec {{learn2rag_path}}/services/open-webui/.venv/bin/uvicorn open_webui.main:app --host 0.0.0.0 --port {{ports.ui}} --forwarded-allow-ips '*'
        {% endif %}
    environment:
      LEARN2RAG_PATH: '{{learn2rag_path}}'
      DATA_DIR: '{{storage_path}}/open-webui-data'
      DEFAULT_LOCALE: 'de'
      ENABLE_OPENAI_API: 'True'
      OPENAI_API_BASE_URL: 'http://localhost:{{ports.open_webui_pipelines}}'
      OPENAI_API_KEY: '0p3n-w3bu!'
      ENABLE_OLLAMA_API: 'False'
      ENABLE_PERSISTENT_CONFIG: 'False'
      ENABLE_TITLE_GENERATION: 'False'
      GLOBAL_LOG_LEVEL: 'WARNING'
      OFFLINE_MODE: 'True'
      USER_PERMISSIONS_CHAT_FILE_UPLOAD: 'False'
      USER_PERMISSIONS_CHAT_TEMPORARY_ENFORCED: 'True'
      USER_PERMISSIONS_FEATURES_CODE_INTERPRETER: 'False'
      USER_PERMISSIONS_FEATURES_IMAGE_GENERATION: 'False'
      USER_PERMISSIONS_FEATURES_WEB_SEARCH: 'False'
      #!!! {% if False and config.get("SIMPLE_AUTH") %}
      # TODO: Upgrade openwebui and use this (WEBUI_ADMIN_EMAIL etc)
      ENABLE_SIGNUP: 'False'
      WEBUI_AUTH: 'True'
      WEBUI_ADMIN_EMAIL: '{{config["SIMPLE_AUTH"].get("username", "")}}'
      WEBUI_ADMIN_NAME: '{{config["SIMPLE_AUTH"].get("username", "")}}'
      WEBUI_ADMIN_PASSWORD:  '{{config["SIMPLE_AUTH"].get("password", "")}}'
      #!!! {% else %}
      # https://docs.openwebui.com/getting-started/env-configuration/#webui_auth
      # "turning off authentication is only possible for fresh installations without any existing users"
      ENABLE_SIGNUP: 'True'
      #!!! {% if not config.get("SIMPLE_AUTH") %}
      WEBUI_AUTH: 'False'
      #!!! {% endif %}
      #!!! {% endif %}
      WEBUI_NAME: 'Learn2RAG'
      PUBLIC_URL: '{{learn2rag_scheme}}://{{learn2rag_hostname}}:{{ports.ui}}/'
    healthcheck:
      # TODO: We only support ['CMD', 'curl', '-f', ...]
      test: ['CMD', 'curl', '-f', '{{learn2rag_scheme}}://localhost:{{ports.ui}}/health']
  # # Only needed if WEBUI_AUTH is True for open-webui
  #!!! {% if config.get("SIMPLE_AUTH") %}
  # TODO: Upgrade openwebui and remove this completely
  open-webui-setup:
    working_dir: '{{storage_path}}'
    command: ['bash', '-eu', '{{learn2rag_path}}/services/setup-open-webui']
    environment:
      WEBUI_URL: '{{learn2rag_scheme}}://{{learn2rag_hostname}}:{{ports.ui}}/'
      ADMIN_USER_EMAIL: '{{config["SIMPLE_AUTH"].get("username", "")}}'
      ADMIN_USER_PASSWORD: '{{config["SIMPLE_AUTH"].get("password", "")}}'
  #!!! {% endif %}
  openwebui-pipelines:
    working_dir: 'services/open-webui-pipelines'
    command: ['{{learn2rag_path}}/services/start-open-webui-pipelines{% if is_windows %}.exe{% endif %}']
    environment:
      LEARN2RAG_PATH: '{{learn2rag_path}}'
      GLOBAL_LOG_LEVEL: 'WARNING'
      PIPELINE_STREAM_URL: 'http://127.0.0.1:{{ports.pipeline}}/stream'
      PIPELINES_DIR: '{{learn2rag_path}}/open-webui-pipelines'
      HOST: '127.0.0.1'
      PORT: '{{ports.open_webui_pipelines}}'
  qdrant:
    working_dir: '{{storage_path}}'
    command:
      - '{{learn2rag_path}}/services/qdrant/qdrant{% if is_windows %}.exe{% endif %}'
      - '--config-path'
      - '{{storage_path}}/qdrant_config.yml'
    # https://qdrant.tech/documentation/guides/configuration/
    environment:
      QDRANT__LOG_LEVEL: 'ERROR'
      QDRANT__SERVICE__HOST: '127.0.0.1'
      QDRANT__SERVICE__HTTP_PORT: '{{ports.qdrant_http}}'
      QDRANT__TELEMETRY_DISABLED: 'true'
  main:
    working_dir: '{{storage_path}}'
    command:
      - '{{learn2rag_path}}/configurator{% if is_windows %}.exe{% endif %}'
      - 'learn2rag.pipeline'
      - '--logging-config'
      - '{{storage_path}}/logging_config.yml'
    environment:
      LEARN2RAG_PATH: '{{learn2rag_path}}'
      LEARN2RAG_PIPELINE_PORT: '{{ports.pipeline}}'
      QDRANT__SERVICE__HTTP_PORT: '{{ports.qdrant_http}}'
      QDRANT_URL: 'http://127.0.0.1:{{ports.qdrant_http}}'
      PIPELINE_USER_CONFIG: '{{storage_path}}/basic_user_config.json'
      IMPORTER_CONFIG: '{{storage_path}}/importer_config.json'
      PIPELINE_OPT_CONFIG: '{{learn2rag_path}}/learn2rag/pipeline/opt_config.json'
      LANGCHAIN_API_KEY: '1'
      LANGCHAIN_TRACING_V2: 'false'
      LLM_API_TYPE: '{{language_model.api}}'
      LLM_API_URL: '{{language_model.url}}'
      LLM_API_TOKEN: '{{language_model.token}}'
      LLM_API_MODEL: '{{language_model.model}}'
