version: 1
formatters:
  colored:
    class: colorlog.ColoredFormatter
    format: "%(log_color)s%(asctime)s %(levelname)-8s %(name)s %(message)s"
handlers:
  display:
    class: logging.StreamHandler
    level: INFO
    formatter: colored
    stream: ext://sys.stderr
root:
  level: INFO
  handlers: [display]
