# This file is not seen or supposed to be changed by users.
# The user-provided configuration file extends this one.
# (config.yml next to the project root or executable)
SUGGESTED_MODELS:
  gpt_oss_20b:
    label: OpenAI GPT-OSS (20B)
    description: |
      Download size: 14GB
    link: https://ollama.com/library/gpt-oss:20b
    ollama: pull
    config:
      api: ChatOllama
      model: gpt-oss:20b
  gemma4_26b:
    label: Google Gemma 4 (26B)
    description: |
      Download size: ~15GB
    link: https://ollama.com/library/gemma4
    ollama: pull
    config:
      api: ChatOllama
      model: gemma4:26b
  llama3.3_70b:
    label: Meta Llama 3.3
    description: |
      Download size: 43GB
    link: https://ollama.com/library/llama3.3
    ollama: pull
    config:
      api: ChatOllama
      model: llama3.3:70b
  tinyllama:
    label: TinyLlama
    image: models/tinyllama.png
    link: https://github.com/jzhang38/TinyLlama
    ollama: pull
    config:
      api: ChatOllama
      model: tinyllama:latest
