name: test
on: push
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13.5'
          cache: 'poetry'
      - run: poetry install --no-root
      - run: poetry run mypy learn2rag
      - run: poetry run pytest
